package com.mygdx.game.desktop;

import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.mygdx.game.FirstGame;
/**
 * Automatically generated by libgdx
 * 
 * @author Malyq McELroy
 *
 */
public class DesktopLauncher {
	public static void main (String[] arg) {
		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		config.width = FirstGame.WIDTH;
		config.height = FirstGame.HEIGHT;
		config.title = FirstGame.title;
		new LwjglApplication(new FirstGame(), config);
	}
}
